<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$form = $this->form;
$form->setAttribute('action', $this->url(
                'login/process', array(
            'action' => 'authenticate',
                )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

if ($this->messages) {
    echo '<ul>';
    foreach ($this->messages as $message) {
        echo '<li>' . $message . '</li>';
    }
    echo '</ul>';
}

