<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$title = 'Supprimer un film';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Etes-vous sûr de vouloir supprimer 
     '<?php echo $this->escapeHtml($film->title); ?>' de
     '<?php echo $this->escapeHtml($film->realisateur); ?>' de catégorie 
     '<?php echo $this->escapeHtml($film->categorie); ?>' avec le(s) acteur(s) 
     '<?php echo $this->escapeHtml($film->acteur); ?>' et d'un prix de 
     '<?php echo $this->escapeHtml($film->prix_location); ?>'?
 </p>
 <?php
 $url = $this->url('film', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $film->id; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>
